import { Component, OnInit } from '@angular/core';
import { SelectItem } from 'primeng/api';
import { MainMenuService } from '../../../../shared/services/main-menu.service';

interface Icons {
  name: string;
  code: string;
}

@Component({
  selector: 'app-icon-lib',
  templateUrl: './icon-lib.component.html',
  styleUrls: ['./icon-lib.component.scss']
})
export class IconLibComponent implements OnInit {

  icons: Icons[];
  iconName: string;

  iconSizes: SelectItem[];
  selectedSize: string;

  constructor(public mainMenu: MainMenuService) { }

  /**
   * 화면 초기설정
   * Select button을 활용하여 아이콘 크기설정
   * 아이콘 Fulll List 설정
   */
  ngOnInit() {
    this.selectedSize = "icon-3x";

    this.iconSizes = [
      { label: '1X', value: 'icon-1x' },
      { label: '2X', value: 'icon-2x' },
      { label: '3X', value: 'icon-3x' },
      { label: '4X', value: 'icon-4x' },
      { label: '5X', value: 'icon-5x' }
    ];

    this.icons = [
      { name: 'acceleration', code: 'icon-acceleration' },
      { name: 'add', code: 'icon-add' },
      { name: 'air_conditioning', code: 'icon-air_conditioning' },
      { name: 'alarm', code: 'icon-alarm' },
      { name: 'alert', code: 'icon-alert' },
      { name: 'angry', code: 'icon-angry' },
      { name: 'answer_in_4_hours', code: 'icon-answer_in_4_hours' },
      { name: 'app', code: 'icon-app' },
      { name: 'apps', code: 'icon-apps' },
      { name: 'arrow_down_1', code: 'icon-arrow_down_1' },
      { name: 'arrow_down_2', code: 'icon-arrow_down_2' },
      { name: 'arrow_down_left_1', code: 'icon-arrow_down_left_1' },
      { name: 'arrow_down_left_2', code: 'icon-arrow_down_left_2' },
      { name: 'arrow_down_right_1', code: 'icon-arrow_down_right_1' },
      { name: 'arrow_down_right_2', code: 'icon-arrow_down_right_2' },
      { name: 'arrow_left_1', code: 'icon-arrow_left_1' },
      { name: 'arrow_left_2', code: 'icon-arrow_left_2' },
      { name: 'arrow_right_1', code: 'icon-arrow_right_1' },
      { name: 'arrow_right_2', code: 'icon-arrow_right_2' },
      { name: 'arrow_up_1', code: 'icon-arrow_up_1' },
      { name: 'arrow_up_2', code: 'icon-arrow_up_2' },
      { name: 'arrow_up_left_1', code: 'icon-arrow_up_left_1' },
      { name: 'arrow_up_left_2', code: 'icon-arrow_up_left_2' },
      { name: 'arrow_up_right_1', code: 'icon-arrow_up_right_1' },
      { name: 'arrow_up_right_2', code: 'icon-arrow_up_right_2' },
      { name: 'basket', code: 'icon-basket' },
      { name: 'battery_excellent', code: 'icon-battery_excellent' },
      { name: 'battery_good', code: 'icon-battery_good' },
      { name: 'battery_leasing', code: 'icon-battery_leasing' },
      { name: 'battery_low', code: 'icon-battery_low' },
      { name: 'battery_very_good', code: 'icon-battery_very_good' },
      { name: 'battery_very_low', code: 'icon-battery_very_low' },
      { name: 'battery', code: 'icon-battery' },
      { name: 'bike', code: 'icon-bike' },
      { name: 'bookmark', code: 'icon-bookmark' },
      { name: 'box_123', code: 'icon-box_123' },
      { name: 'box_269', code: 'icon-box_269' },
      { name: 'braking_217', code: 'icon-braking_217' },
      { name: 'braking_241', code: 'icon-braking_241' },
      { name: 'breakdown', code: 'icon-breakdown' },
      { name: 'bulleted_list', code: 'icon-bulleted_list' },
      { name: 'calculator', code: 'icon-calculator' },
      { name: 'calendar', code: 'icon-calendar' },
      { name: 'campervan', code: 'icon-campervan' },
      { name: 'car_body', code: 'icon-car_body' },
      { name: 'car_dealership', code: 'icon-car_dealership' },
      { name: 'car_elevator', code: 'icon-car_elevator' },
      { name: 'car_park', code: 'icon-car_park' },
      { name: 'car_range', code: 'icon-car_range' },
      { name: 'car_restitution', code: 'icon-car_restitution' },
      { name: 'car_review', code: 'icon-car_review' },
      { name: 'car_servicing', code: 'icon-car_servicing' },
      { name: 'car_sheet', code: 'icon-car_sheet' },
      { name: 'car', code: 'icon-car' },
      { name: 'cdv', code: 'icon-cdv' },
      { name: 'chart', code: 'icon-chart' },
      { name: 'chassis_cab', code: 'icon-chassis_cab' },
      { name: 'check_list_ok', code: 'icon-check_list_ok' },
      { name: 'check_list', code: 'icon-check_list' },
      { name: 'check_oil', code: 'icon-check_oil' },
      { name: 'check_tire', code: 'icon-check_tire' },
      { name: 'city', code: 'icon-city' },
      { name: 'cloudy_1', code: 'icon-cloudy_1' },
      { name: 'cloudy_2', code: 'icon-cloudy_2' },
      { name: 'coins', code: 'icon-coins' },
      { name: 'comment', code: 'icon-comment' },
      { name: 'compact_van', code: 'icon-compact_van' },
      { name: 'compare', code: 'icon-compare' },
      { name: 'compass', code: 'icon-compass' },
      { name: 'contact', code: 'icon-contact' },
      { name: 'cookies', code: 'icon-cookies' },
      { name: 'cool', code: 'icon-cool' },
      { name: 'cooling_liquid', code: 'icon-cooling_liquid' },
      { name: 'countryside', code: 'icon-countryside' },
      { name: 'coupe', code: 'icon-coupe' },
      { name: 'crash', code: 'icon-crash' },
      { name: 'credit_card', code: 'icon-credit_card' },
      { name: 'custom', code: 'icon-custom' },
      { name: 'damper', code: 'icon-damper' },
      { name: 'data', code: 'icon-data' },
      { name: 'de_zoom', code: 'icon-de_zoom' },
      { name: 'decrease_text', code: 'icon-decrease_text' },
      { name: 'delete', code: 'icon-delete' },
      { name: 'desktop', code: 'icon-desktop' },
      { name: 'dialog', code: 'icon-dialog' },
      { name: 'dimmend_headlights', code: 'icon-dimmend_headlights' },
      { name: 'discussion', code: 'icon-discussion' },
      { name: 'door', code: 'icon-door' },
      { name: 'double_piston', code: 'icon-double_piston' },
      { name: 'double_tap_gesture_1', code: 'icon-double_tap_gesture_1' },
      { name: 'double_tap_gesture_2', code: 'icon-double_tap_gesture_2' },
      { name: 'double_tap_gesture_3', code: 'icon-double_tap_gesture_3' },
      { name: 'download', code: 'icon-download' },
      { name: 'drag_gesture_1', code: 'icon-drag_gesture_1' },
      { name: 'drag_gesture_2', code: 'icon-drag_gesture_2' },
      { name: 'drag_gesture_3', code: 'icon-drag_gesture_3' },
      { name: 'draining', code: 'icon-draining' },
      { name: 'dump_truck', code: 'icon-dump_truck' },
      { name: 'eco_2_chart', code: 'icon-eco_2_chart' },
      { name: 'eco_2', code: 'icon-eco_2' },
      { name: 'edit', code: 'icon-edit' },
      { name: 'electirc_power', code: 'icon-electirc_power' },
      { name: 'electric_engine', code: 'icon-electric_engine' },
      { name: 'electric_plug', code: 'icon-electric_plug' },
      { name: 'electric_vehicle', code: 'icon-electric_vehicle' },
      { name: 'email_sheet', code: 'icon-email_sheet' },
      { name: 'emergency', code: 'icon-emergency' },
      { name: 'engine_capacity', code: 'icon-engine_capacity' },
      { name: 'engine', code: 'icon-engine' },
      { name: 'estate', code: 'icon-estate' },
      { name: 'euro', code: 'icon-euro' },
      { name: 'exhaust', code: 'icon-exhaust' },
      { name: 'expand', code: 'icon-expand' },
      { name: 'factory', code: 'icon-factory' },
      { name: 'favourite_car', code: 'icon-favourite_car' },
      { name: 'favourite_sheet', code: 'icon-favourite_sheet' },
      { name: 'favourite', code: 'icon-favourite' },
      { name: 'file_download', code: 'icon-file_download' },
      { name: 'files', code: 'icon-files' },
      { name: 'filter_1', code: 'icon-filter_1' },
      { name: 'filter_2', code: 'icon-filter_2' },
      { name: 'flag', code: 'icon-flag' },
      { name: 'folder', code: 'icon-folder' },
      { name: 'foundry', code: 'icon-foundry' },
      { name: 'frame', code: 'icon-frame' },
      { name: 'front_fog_lights', code: 'icon-front_fog_lights' },
      { name: 'fuel_excellent', code: 'icon-fuel_excellent' },
      { name: 'fuel_good', code: 'icon-fuel_good' },
      { name: 'fuel_low', code: 'icon-fuel_low' },
      { name: 'fuel_station', code: 'icon-fuel_station' },
      { name: 'fuel_very_good', code: 'icon-fuel_very_good' },
      { name: 'fuel_very_low', code: 'icon-fuel_very_low' },
      { name: 'full_screen', code: 'icon-full_screen' },
      { name: 'gearbox_1', code: 'icon-gearbox_1' },
      { name: 'gearbox_2', code: 'icon-gearbox_2' },
      { name: 'gearbox_3', code: 'icon-gearbox_3' },
      { name: 'gearbox_4', code: 'icon-gearbox_4' },
      { name: 'group', code: 'icon-group' },
      { name: 'guarantee', code: 'icon-guarantee' },
      { name: 'happy', code: 'icon-happy' },
      { name: 'hatchback', code: 'icon-hatchback' },
      { name: 'headlights', code: 'icon-headlights' },
      { name: 'helmet', code: 'icon-helmet' },
      { name: 'hold_gesture_1', code: 'icon-hold_gesture_1' },
      { name: 'hold_gesture_2', code: 'icon-hold_gesture_2' },
      { name: 'hold_gesture_3', code: 'icon-hold_gesture_3' },
      { name: 'home', code: 'icon-home' },
      { name: 'hybrid', code: 'icon-hybrid' },
      { name: 'idea', code: 'icon-idea' },
      { name: 'increase_text', code: 'icon-increase_text' },
      { name: 'information', code: 'icon-information' },
      { name: 'interior', code: 'icon-interior' },
      { name: 'intervention', code: 'icon-intervention' },
      { name: 'joystick', code: 'icon-joystick' },
      { name: 'keys', code: 'icon-keys' },
      { name: 'ko', code: 'icon-ko' },
      { name: 'kw_engine', code: 'icon-kw_engine' },
      { name: 'laptop', code: 'icon-laptop' },
      { name: 'large_van', code: 'icon-large_van' },
      { name: 'lightning', code: 'icon-lightning' },
      { name: 'link_out', code: 'icon-link_out' },
      { name: 'links', code: 'icon-links' },
      { name: 'luggages', code: 'icon-luggages' },
      { name: 'mechanical_1', code: 'icon-mechanical_1' },
      { name: 'mechanical_2', code: 'icon-mechanical_2' },
      { name: 'menu', code: 'icon-menu' },
      { name: 'minibus', code: 'icon-minibus' },
      { name: 'minimize', code: 'icon-minimize' },
      { name: 'mobile', code: 'icon-mobile' },
      { name: 'mobility_help', code: 'icon-mobility_help' },
      { name: 'money', code: 'icon-money' },
      { name: 'more', code: 'icon-more' },
      { name: 'motorway', code: 'icon-motorway' },
      { name: 'mpv', code: 'icon-mpv' },
      { name: 'music', code: 'icon-music' },
      { name: 'new_bookmark', code: 'icon-new_bookmark' },
      { name: 'next', code: 'icon-next' },
      { name: 'no_battery', code: 'icon-no_battery' },
      { name: 'no_fuel', code: 'icon-no_fuel' },
      { name: 'no_lights', code: 'icon-no_lights' },
      { name: 'no_sound', code: 'icon-no_sound' },
      { name: 'no', code: 'icon-no' },
      { name: 'not_happy', code: 'icon-not_happy' },
      { name: 'not_plugged', code: 'icon-not_plugged' },
      { name: 'oil_engine', code: 'icon-oil_engine' },
      { name: 'oil_filter', code: 'icon-oil_filter' },
      { name: 'ok_21', code: 'icon-ok_21' },
      { name: 'ok_101', code: 'icon-ok_101' },
      { name: 'organisation', code: 'icon-organisation' },
      { name: 'paint_bucket', code: 'icon-paint_bucket' },
      { name: 'pannel', code: 'icon-pannel' },
      { name: 'parking', code: 'icon-parking' },
      { name: 'partly_cloudy_1', code: 'icon-partly_cloudy_1' },
      { name: 'partly_cloudy_2', code: 'icon-partly_cloudy_2' },
      { name: 'partly_lightning_1', code: 'icon-partly_lightning_1' },
      { name: 'partly_lightning_2', code: 'icon-partly_lightning_2' },
      { name: 'partly_raining_1', code: 'icon-partly_raining_1' },
      { name: 'partly_raining_2', code: 'icon-partly_raining_2' },
      { name: 'partly_snowing_1', code: 'icon-partly_snowing_1' },
      { name: 'partly_snowing_2', code: 'icon-partly_snowing_2' },
      { name: 'passenger_cdv', code: 'icon-passenger_cdv' },
      { name: 'pause', code: 'icon-pause' },
      { name: 'pdf_sheet', code: 'icon-pdf_sheet' },
      { name: 'phone', code: 'icon-phone' },
      { name: 'photo', code: 'icon-photo' },
      { name: 'pick_up', code: 'icon-pick_up' },
      { name: 'pin', code: 'icon-pin' },
      { name: 'piston', code: 'icon-piston' },
      { name: 'planet', code: 'icon-planet' },
      { name: 'play', code: 'icon-play' },
      { name: 'playload', code: 'icon-playload' },
      { name: 'plugged_ok', code: 'icon-plugged_ok' },
      { name: 'pluggin_hybrid', code: 'icon-pluggin_hybrid' },
      { name: 'podcast', code: 'icon-podcast' },
      { name: 'previous', code: 'icon-previous' },
      { name: 'print', code: 'icon-print' },
      { name: 'prize', code: 'icon-prize' },
      { name: 'progression', code: 'icon-progression' },
      { name: 'promo', code: 'icon-promo' },
      { name: 'pumping', code: 'icon-pumping' },
      { name: 'question', code: 'icon-question' },
      { name: 'race', code: 'icon-race' },
      { name: 'raining_1', code: 'icon-raining_1' },
      { name: 'raining_2', code: 'icon-raining_2' },
      { name: 'rapid_charging_port', code: 'icon-rapid_charging_port' },
      { name: 'receive', code: 'icon-receive' },
      { name: 'refresh_configuration', code: 'icon-refresh_configuration' },
      { name: 'refresh', code: 'icon-refresh' },
      { name: 'reload', code: 'icon-reload' },
      { name: 'reminder', code: 'icon-reminder' },
      { name: 'renault_rent', code: 'icon-renault_rent' },
      { name: 'reset_coins', code: 'icon-reset_coins' },
      { name: 'roadster', code: 'icon-roadster' },
      { name: 'sales', code: 'icon-sales' },
      { name: 'save', code: 'icon-save' },
      { name: 'scale_gesture_1', code: 'icon-scale_gesture_1' },
      { name: 'scale_gesture_2', code: 'icon-scale_gesture_2' },
      { name: 'scale_gesture_3', code: 'icon-scale_gesture_3' },
      { name: 'scroll_gesture_1', code: 'icon-scroll_gesture_1' },
      { name: 'scroll_gesture_2', code: 'icon-scroll_gesture_2' },
      { name: 'scroll_gesture_3', code: 'icon-scroll_gesture_3' },
      { name: 'scroll', code: 'icon-scroll' },
      { name: 'search', code: 'icon-search' },
      { name: 'second_hand', code: 'icon-second_hand' },
      { name: 'sedan', code: 'icon-sedan' },
      { name: 'sellerie', code: 'icon-sellerie' },
      { name: 'send_03', code: 'icon-send_03' },
      { name: 'send_98', code: 'icon-send_98' },
      { name: 'settings_sheet', code: 'icon-settings_sheet' },
      { name: 'settings', code: 'icon-settings' },
      { name: 'share_1', code: 'icon-share_1' },
      { name: 'share_2', code: 'icon-share_2' },
      { name: 'sheet', code: 'icon-sheet' },
      { name: 'shop_bag', code: 'icon-shop_bag' },
      { name: 'shuttle', code: 'icon-shuttle' },
      { name: 'slide', code: 'icon-slide' },
      { name: 'snow_box', code: 'icon-snow_box' },
      { name: 'snowing', code: 'icon-snowing' },
      { name: 'sound', code: 'icon-sound' },
      { name: 'spare_parts', code: 'icon-spare_parts' },
      { name: 'speedometer', code: 'icon-speedometer' },
      { name: 'split_rotate_gesture_1', code: 'icon-split_rotate_gesture_1' },
      { name: 'split_rotate_gesture_2', code: 'icon-split_rotate_gesture_2' },
      { name: 'split_rotate_gesture_3', code: 'icon-split_rotate_gesture_3' },
      { name: 'spray_gun', code: 'icon-spray_gun' },
      { name: 'spray', code: 'icon-spray' },
      { name: 'standard_charging_port', code: 'icon-standard_charging_port' },
      { name: 'start_again', code: 'icon-start_again' },
      { name: 'steering_wheel', code: 'icon-steering_wheel' },
      { name: 'stop', code: 'icon-stop' },
      { name: 'stopwatch', code: 'icon-stopwatch' },
      { name: 'sunny', code: 'icon-sunny' },
      { name: 'surprise', code: 'icon-surprise' },
      { name: 'suv', code: 'icon-suv' },
      { name: 'swipe_gesture_1', code: 'icon-swipe_gesture_1' },
      { name: 'swipe_gesture_2', code: 'icon-swipe_gesture_2' },
      { name: 'swipe_gesture_3', code: 'icon-swipe_gesture_3' },
      { name: 'tablet', code: 'icon-tablet' },
      { name: 'tap_gesture_1', code: 'icon-tap_gesture_1' },
      { name: 'tap_gesture_2', code: 'icon-tap_gesture_2' },
      { name: 'tap_gesture_3', code: 'icon-tap_gesture_3' },
      { name: 'target', code: 'icon-target' },
      { name: 'television', code: 'icon-television' },
      { name: 'timing_belt', code: 'icon-timing_belt' },
      { name: 'touch', code: 'icon-touch' },
      { name: 'tire_and_rim', code: 'icon-tire_and_rim' },
      { name: 'tire', code: 'icon-tire' },
      { name: 'undecided', code: 'icon-undecided' },
      { name: 'upload', code: 'icon-upload' },
      { name: 'usb', code: 'icon-usb' },
      { name: 'user', code: 'icon-user' },
      { name: 'very_happy', code: 'icon-very_happy' },
      { name: 'video', code: 'icon-video' },
      { name: 'view', code: 'icon-view' },
      { name: 'wall_charging_port', code: 'icon-wall_charging_port' },
      { name: 'weight', code: 'icon-weight' },
      { name: 'welcome', code: 'icon-welcome' },
      { name: 'wifi', code: 'icon-wifi' },
      { name: 'windscreen', code: 'icon-windscreen' },
      { name: 'windshield_wipers_ok', code: 'icon-windshield_wipers_ok' },
      { name: 'windshield_wipers', code: 'icon-windshield_wipers' },
      { name: 'windy', code: 'icon-windy' },
      { name: 'zoom', code: 'icon-zoom' }

    ];

  }

}
